### ISSUE TITLE
Calling methods

### ISSUE THREAD

**Issue by chrismurrph** [fn-fx/fn-fx#14]
Would it be possible to have an example of calling a method on a ui object? As an example this does not work:

    (def transition (ui/parallel-transition a-rect a-translate))
    (.play transition)

**Comment by DonyorM** [comment]
I would also really appreciate knowing how to do this.

**Comment by chrismurrph** [comment]
Thanks for clarifying. I asked that question more than a year ago, and no longer have that use case, as have 'moved on' from wanting to do whatever I was planing to use fn-fx for.

**Comment by paulrd** [comment]
I'm wondering what would be the easiest work-around for this. I want to animate some text as shown [here](https://github.com/Apress/pro-javafx-9/blob/master/chapter1/HelloEarthRise/src/main/java/projavafx/helloearthrise/ui/HelloEarthRiseMain.java):

**Comment by roti** [comment]
I think the easiest way would be to get the Java FX `Node` by id. `find-nearest-by-id` and `find-child-by-id` from `fn-fx.fx-tree-search` do this. I guess they were written for internal use, but they are public so you can use them directly. If they are to be part of fn-fx's API, some improvement is needed.
