### ISSUE TITLE
Has development of  this library been abandoned?  

### ISSUE THREAD

**Issue by dabrazhe** [fn-fx/fn-fx#33]
The last commits are from year ago..

**Comment by pmonks** [comment]
A few folks are looking to resurrect development and would love you help.  We're in the process of transferring this repository to the https://github.com/fn-fx org, to make it easier to delegate responsibilities.

Please let me know if you're interested in joining, and I'll send you an invite.

**Comment by dabrazhe** [comment]
Why resurrect it now? JavaFX  will be decoupled from the sdk, won't this put in danger of being discontinued?

**Comment by pmonks** [comment]
@dabrazhe I’ve already prepared a basic port of fn-fx to OpenJFX (the unbundled, go-forward version of Java FX) - see https://github.com/fn-fx/fn-fx-openjfx

**Comment by pmonks** [comment]
Just to close this out - development hasn't been abandoned.  @halgari graciously transferred the code to an organisation, which makes "crowdsourcing" the development and maintenance easier.

It would be absolutely fantastic if interested folks (@dabrazhe?) were to join us in ongoing development!
