### ISSUE TITLE
Implement release process

### ISSUE THREAD

**Issue by ehartford** [fn-fx/fn-fx#7]
Request implement a release process that publishes to clojars

**Comment by paulrd** [comment]
I republished to clojars as a temporary measure.

**Comment by JeremyCooper** [comment]
Hello, could someone publish "0.5.0" to clojars? Seems the version there is outdated.

**Comment by pmonks** [comment]
Closely related to issue #43.

**Comment by pmonks** [comment]
Although `0.5.0` is not yet released, we have started automatically publishing `0.5.0-SNAPSHOT` releases to Clojars from `master`:
* https://clojars.org/fn-fx/fn-fx-javafx
* https://clojars.org/fn-fx/fn-fx-openjfx11

Contributions to help us push towards a final `0.5.0` release very welcome!
